version: "2.5"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    networks:
      - backend
    ports:
      - "4000:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/api/openapi.yaml
  api:
    build: ./calculator-api
    container_name: app
    env_file: ./calculator-api/.env
    networks:
      - backend
    ports:
      - 3000:3000
networks:
  backend:
    name: "api_docs"
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.6.0.0/16
          ip_range: 10.6.0.0/24
          gateway: 10.6.0.1
          aux_addresses:
            swagger: 10.6.0.2
            api: 10.6.0.3
